name: CI to Docker Hub

on: [push, pull_request]

jobs:
  build1:
    name: build_group1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
         - clr-wsl-base
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v1
    - name: Login to DockerHub
      if: success() && github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Build
      run: | 
        sudo apt-get purge moby-engine moby-cli 
        sudo apt-get install docker.io bats -f
        sudo modprobe -r overlay
        sudo modprobe overlay redirect_dir=off
        sudo systemctl restart docker
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./${{matrix.node}}/
        file: ./${{matrix.node}}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.node}}:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}